
import { Play } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const play = Play({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "DayaMall",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={play.className}>
      <body>
      <Toaster position="top-right" reverseOrder={false} />
        {children}
        </body>
    </html>
  );
}
